name: Build WalletGenerator

on: 
 push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Fix ssh errors
      run: find . -type f -print0 | xargs -0 sed -i 's%ssh://git@github.com/%https://github.com/%'
      continue-on-error: true
    - name: Set up libraries
      run: npm ci
    - name: Build website
      run: npm run public
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
  standalone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Fix ssh errors
      run: find . -type f -print0 | xargs -0 sed -i 's%ssh://git@github.com/%https://github.com/%'
      continue-on-error: true
    - name: Set up libraries
      run: npm ci
    - name: Build website
      continue-on-error: true
      run: |
        node ./util/postinstall.js
        node ./util/gen.js
        NODE_OPTIONS=--max-old-space-size=7000 npm run standalone
    - name: Upload built HTML
      uses: actions/upload-artifact@v2
      with:
        name: standalone
        path: public/standalone.html
