name: Deploy repository to Netlify

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}

jobs:
  netlify:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Set up Netlify
        run: npm install netlify-cli -g
      - name: Build and deploy
        run: |
          npm run fix-blake2b
          npm install
          netlify build
          netlify deploy --prod
