name: Test WalletGenerator

on: 
 push:
   branches-ignore:
     - gh-pages
 pull_request:
   branches-ignore:
     - gh-pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install deps
      run: |
        sudo ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
        sudo apt update
        sudo env DEBIAN_FRONTEND=noninteractive apt install -y build-essential curl python3 tzdata \
            ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 \
            libatk1.0-0 libatspi2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libdrm2 libexpat1 \
            libgbm1 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 \
            libpangocairo-1.0-0 libx11-6 libx11-xcb1 libxcb-dri3-0 libxcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 wget xdg-utils
    - name: Fix ssh errors
      run: find . -type f -print0 | xargs -0 sed -i 's%https://github.com/%https://github.com/%'
      continue-on-error: true
    - name: Set up libraries
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: npm-logs
        path: /home/runner/.npm/_logs/
